---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Make temp directory for git
      shell: "mkdir -p test"
    - name: Retrieving war file from repo
      git:
        repo: https://github.com/Melody-Tch/Maven-Selenium.git
        dest: test
    - name: moving file1 to tomcat
      shell: "sudo cp /var/lib/jenkins/workspace/ApacheJenkins_master-KJ62CKVCZFGDMZ4FWDQF3YVB2X67VWNSRTZOPXKS2ZK575ZNBT6Q/HelloWorldJSP.war /usr/share/tomcat/webapps"
    - name: moving file2 to tomcat
      shell: "sudo cp /var/lib/jenkins/workspace/ApacheJenkins_master-KJ62CKVCZFGDMZ4FWDQF3YVB2X67VWNSRTZOPXKS2ZK575ZNBT6Q/InitialProjectTest.war /usr/share/tomcat/webapps"
    - name: Restart Tom Cat
      shell: "sudo systemctl restart tomcat"