---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install Tomcat
      shell: "sudo yum install -y tomcat"
    - name: Install Tomcat extra
      shell: "sudo yum install -y tomcat-webapps tomcat-admin-webapps"
    - name: Enable tomcat
      shell: "sudo systemctl enable tomcat"
    - name: Start tomcat
      shell: "sudo systemctl start tomcat"
