---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Install apache
      shell: "sudo yum install -y httpd"
    - name: Enable httpd
      shell: "sudo systemctl enable httpd.service"
    - name: Start httpd
      shell: "sudo systemctl start httpd.service"