---
- hosts: localhost
  remote_user: root
  tasks:
    - name: Allow Permission for apache
      shell: "sudo /usr/sbin/setsebool -P httpd_can_network_connect 1"
    - name: reverse proxy apache to tomcat
      shell: "sudo mv /var/lib/jenkins/workspace/ApacheJenkins_master-KJ62CKVCZFGDMZ4FWDQF3YVB2X67VWNSRTZOPXKS2ZK575ZNBT6Q/tomcat.conf /etc/httpd/conf.d"
    - name: permission ofr tomcat.conf
      shell: "sudo chcon -R --reference=/etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/tomcat.conf"
    - name: restart apache
      shell: "sudo systemctl restart httpd.service"